vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        reporte:
            uri_prefix: /images/reporte
            upload_destination: '%kernel.project_dir%/public/images/reporte'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
